### PR TITLE
Fix broken JavaScript link

### PR DESCRIPTION
**Pull request by furzeface**
:smile:

### CODE REVIEW

**Comment by MaximAbramchuck** [comment]
Thanks!

**Comment by furzeface** [comment]
Awesome list by the way, thank you! :sunglasses:

**Comment by MaximAbramchuck** [comment]
@furzeface thanks :)
if you have some more tips how can I improve this list, or some links seem bad or outdated to you, feel free to open a PR

**Comment by MaximAbramchuck** [comment]
@furzeface \cc https://github.com/MaximAbramchuck/awesome-interviews/issues/37

**Comment by furzeface** [comment]
I will do, I'm sure I kept a list of resources somewhere for interviews that I conducted for front end dev jobs. I shall find it out and PR fi there's anything useful on there that you've not already got.

**Comment by MaximAbramchuck** [comment]
@furzeface thanks!
also you can review links related to your speciality and remove that links that you think is weird or outdated :)

**Comment by furzeface** [comment]
Sure, I'm going to be looking through a load of the JavaScript ones later on so I will make a note of any that aren't all that useful :+1:

**Pull request merged**
