### PR TITLE
Add link to front-end interview questions

### PR DESCRIPTION
**Pull request by starandtina**
Add link to front-end interview questions.

### CODE REVIEW

**Comment by MaximAbramchuck** [comment]
@starandtina update please commit name like `Add link to front-end interview questions`.

**Comment by MaximAbramchuck** [comment]
@starandtina I meant a commit name, not a PR repo. Just do `ammend` and then `forced update`.
When it will be ready, ping me here, in comments.

**Comment by starandtina** [comment]
@MaximAbramchuck  Thanks! It's ready now.

**Comment by MaximAbramchuck** [comment]
@starandtina Thanks a lot for your contribution! :)

**Pull request merged**
